### ISSUE TITLE
Navigation bar / header UI

### ISSUE THREAD

**Issue by arjun27** [arjun27/toilet-paper-app#7]
need a simple to use navigation experience between the home and submit pages. all the elements are in place, they need to be put into a nicer looking UI

**Comment by sampoorna** [comment]
Couldn't get the logo to show for some reason.

**Comment by arjun27** [comment]
fixed in https://github.com/arjun27/toilet-paper-app/commit/ad3e7cca074c49c1213cc2d0f8a2e8c3a8951e0c
